[
    {"owner": "anonymous", "date": "", "rating": "0", "body": ""},
    {"owner": "Cesar Martinez", "date": "April 11, 2015", "rating": "100", "body": " Aa It is a hard game but it is so great man. It\u0027s so addicting I can\u0027t stop playing it😆😆😆😂😂😂😂   Full Review   "},
    {"owner": "Kindra Anderson", "date": "April 12, 2015", "rating": "80", "body": " The game is hard I am only 11 so don\u0027t judge I think this game is very hard especially if you have ADHD   Full Review   "},
    {"owner": "Kacey Shurety", "date": "April 11, 2015", "rating": "100", "body": "  Amazing no problems and fun   Full Review   "},
    {"owner": "Cody Lowe", "date": "April 12, 2015", "rating": "100", "body": " OMG i put 5 star not for how good it is for how frustrating it is i felt like throwing my phone threw the window and i still carnt get past the 31 lvl   Full Review   "},
    {"owner": "Milad Mirzad", "date": "April 12, 2015", "rating": "100", "body": " Bjhj The worst game ever it has a virus do not download   Full Review   "},
    {"owner": "elaine taylor", "date": "April 14, 2015", "rating": "100", "body": "  This is so simple yet quite addictive  trying to get to the next level, a good time waster  game if you have few minutes or hours as you  HAVE  to beat your next  level   Full Review   "},
    {"owner": "erica shije", "date": "April 13, 2015", "rating": "100", "body": " Love it It cool but I  can\u0027t get pass level 11  it\u0027s heard for me   Full Review   "},
    {"owner": "Vlad Claudiu", "date": "April 15, 2015", "rating": "40", "body": " Bug After lvl 93 it jumped to 105 after that 113 after that 120 and it just jumps ahead after i finish a lvl. Why is that??   Full Review   "},
    {"owner": "Crapplejuice 982", "date": "April 14, 2015", "rating": "100", "body": " Brings out my inner Satan Entertaining and challenging. Awesome game.   Full Review   "},
    {"owner": "Pankhuri Atul Prakash", "date": "April 12, 2015", "rating": "100", "body": " I LOVE THIS APP It is so addicting   Full Review   "},
    {"owner": "kyrsten schanuth", "date": "April 13, 2015", "rating": "40", "body": " I love aa its my fav Aa   Full Review   "},
    {"owner": "Frank Lutz", "date": "April 14, 2015", "rating": "100", "body": " AA I love this game by the way im a girl   Full Review   "},
    {"owner": "Dacianna Mosley", "date": "April 14, 2015", "rating": "100", "body": " Its a good game but still have 1question I love aa,ff,th,anduu .but on aa why did it skip level 10?plwase fix!😳😫   Full Review   "},
    {"owner": "Tasha Evans", "date": "April 15, 2015", "rating": "100", "body": " Aa It is so addictive  but so much fun   Full Review   "},
    {"owner": "Josh Richards", "date": "April 11, 2015", "rating": "100", "body": " Gd I\u0027m level 170 atm lol gets hard as well   Full Review   "},
    {"owner": "Aiysha Bootwala", "date": "April 11, 2015", "rating": "100", "body": " Such a good game Luv the game.Expecially wen I\u0027m bored this is the best game .   Full Review   "},
    {"owner": "jordann a", "date": "April 12, 2015", "rating": "60", "body": "  Not bad gets addictive and annoying   Full Review   "},
    {"owner": "Keith Holmes", "date": "April 14, 2015", "rating": "60", "body": " Good - It\u0027s quite addictive and good to pass the time ☆☆☆   Full Review   "},
    {"owner": "Melanie Lunar", "date": "April 14, 2015", "rating": "100", "body": " Loving it This is a fun game I love it\u003d)   Full Review   "},
    {"owner": "ramin Jafari", "date": "April 12, 2015", "rating": "100", "body": "  ویروسی که به شدت مخ ادمو تیلیت میکنه   Full Review   "},
    {"owner": "Lee Johnson", "date": "April 12, 2015", "rating": "20", "body": " grr the lag on this game is stupid and you die even when your not suppose to.....die...   Full Review   "},
    {"owner": "Shally Zarzar", "date": "April 11, 2015", "rating": "20", "body": " Bugs after each update! Can\u0027t close the application.   Full Review   "},
    {"owner": "Kamber Mustafi", "date": "April 14, 2015", "rating": "60", "body": " I like it But i dont now why there exist a buton for rating 😈   Full Review   "},
    {"owner": "Alex Carranza", "date": "April 11, 2015", "rating": "80", "body": " Too many adds It\u0027s okay but too many adds   Full Review   "},
    {"owner": "Aleksa \u0026Scaron;iljić", "date": "April 12, 2015", "rating": "60", "body": " OK je igrica!!! Lenovo S-820t   Full Review   "},
    {"owner": "Wendy Richards", "date": "April 14, 2015", "rating": "60", "body": " I do not like the ads Its not wright that I should have to pay to remove ads   Full Review   "},
    {"owner": "Richard Cotterill", "date": "April 13, 2015", "rating": "60", "body": " How do you exit? Okay game but how do you get out of it?   Full Review   "},
    {"owner": "Swastika Sharma", "date": "April 15, 2015", "rating": "100", "body": " cool it is a very good game but its very VERY addivtive I dont know if that was what they were aiming for   Full Review   "},
    {"owner": "demiana boutros", "date": "April 14, 2015", "rating": "80", "body": " Good game Goat some pointsod game but it\u0027s really frustrating   Full Review   "},
    {"owner": "Jamie Andrews", "date": "April 13, 2015", "rating": "60", "body": "  OK how do you get out of google plus   Full Review   "},
    {"owner": "Simply TeeTee", "date": "April 14, 2015", "rating": "100", "body": " Addition Level55 it hard I can\u0027t beat it   Full Review   "},
    {"owner": "Alimazloum Alialiali", "date": "April 12, 2015", "rating": "100", "body": " The aa Its help people to sho be3refne   Full Review   "},
    {"owner": "Sam Hardisty-green", "date": "April 15, 2015", "rating": "60", "body": " Delayed ads When you\u0027re invited to click to reply an ad will pop up half a second after so it tricks you into clicking it, so frustrating.   Full Review   "},
    {"owner": "Nesma Walid", "date": "April 15, 2015", "rating": "60", "body": "  Couldn\u0027t go a level /levels back   Full Review   "},
    {"owner": "Humzah Abubakar", "date": "April 15, 2015", "rating": "100", "body": " Wow Melanie perez you are right what are you waiting for ? MY LEVEL IS 84   Full Review   "},
    {"owner": "furkan seyhan", "date": "April 15, 2015", "rating": "20", "body": " Annoying glitches Sometimes it shoots the ball to a random place rather than center of the screen   Full Review   "},
    {"owner": "Broddle vs Crowther", "date": "April 12, 2015", "rating": "100", "body": " Frustrating Very frustrating but really addictive   Full Review   "},
    {"owner": "Kylee Patterson", "date": "April 14, 2015", "rating": "20", "body": " Keeps glitching I can\u0027t play a single game without it glitching!!!   Full Review   "},
    {"owner": "Ethan Hoffart", "date": "April 15, 2015", "rating": "100", "body": " Best game ever Its cool   Full Review   "}
]